export const BOARDS_FEATURE_ENABLED =
  typeof __SHADOWCHAT_BOARDS_ENABLED__ !== 'undefined' && __SHADOWCHAT_BOARDS_ENABLED__ === true

export const ESP_ADMIN_FEATURE_ENABLED =
  typeof __SHADOWCHAT_ESP_ADMIN_ENABLED__ !== 'undefined' && __SHADOWCHAT_ESP_ADMIN_ENABLED__ === true

export const ACTIVITY_FEATURE_ENABLED =
  typeof __SHADOWCHAT_ACTIVITY_ENABLED__ !== 'undefined' && __SHADOWCHAT_ACTIVITY_ENABLED__ === true

export const MEMBER_REPORTING_FEATURE_ENABLED =
  typeof __SHADOWCHAT_MEMBER_REPORTING_ENABLED__ !== 'undefined' && __SHADOWCHAT_MEMBER_REPORTING_ENABLED__ === true

export const SHADO_LIVE_PROTOTYPE_ENABLED =
  typeof __SHADOWCHAT_SHADO_LIVE_PROTOTYPE_ENABLED__ !== 'undefined' && __SHADOWCHAT_SHADO_LIVE_PROTOTYPE_ENABLED__ === true

export const CATCH_UP_FEATURE_ENABLED =
  typeof __SHADOWCHAT_CATCH_UP_ENABLED__ !== 'undefined' && __SHADOWCHAT_CATCH_UP_ENABLED__ === true

export const SHADOWCHAT_FEATURES = Object.freeze({
  boards: BOARDS_FEATURE_ENABLED,
  news: BOARDS_FEATURE_ENABLED,
  espAdmin: ESP_ADMIN_FEATURE_ENABLED,
  activity: ACTIVITY_FEATURE_ENABLED,
  memberReporting: MEMBER_REPORTING_FEATURE_ENABLED,
  shadoLivePrototype: SHADO_LIVE_PROTOTYPE_ENABLED,
  catchUp: CATCH_UP_FEATURE_ENABLED,
})
