const ASSET_ROOT = '/games/shadow-runner'
const HOME_ROOT = `${ASSET_ROOT}/home-assets`
const GAMEPLAY_ROOT = `${ASSET_ROOT}/gameplay-assets`
const LEVEL_ROOT = `${ASSET_ROOT}/level-assets`

export const SHADOW_RUNNER_ASSETS = {
  pickerBanner: `${ASSET_ROOT}/shadow-runner-picker-banner.webp`,
  badges: {
    mainMedal: `${ASSET_ROOT}/badges/shadow-runner-main-medal.png`,
    sprint: `${ASSET_ROOT}/badges/shadow-runner-sprint-badge.png`,
    sprintTransparent: `${ASSET_ROOT}/badges/shadow-runner-sprint-badge-transparent.png`,
  },
  music: `${ASSET_ROOT}/audio/castle-bard.mp3`,
  sfx: {
    menuClick: `${ASSET_ROOT}/audio/sfx/menu-click.wav`,
    menuBack: `${ASSET_ROOT}/audio/sfx/menu-back.wav`,
    menuDenied: `${ASSET_ROOT}/audio/sfx/menu-denied.wav`,
    levelSelect: `${ASSET_ROOT}/audio/sfx/level-select.wav`,
    pause: `${ASSET_ROOT}/audio/sfx/pause.wav`,
    resume: `${ASSET_ROOT}/audio/sfx/resume.wav`,
    jump: `${ASSET_ROOT}/audio/sfx/jump.wav`,
    doubleJump: `${ASSET_ROOT}/audio/sfx/double-jump.wav`,
    land: `${ASSET_ROOT}/audio/sfx/land.wav`,
    swordSwing: `${ASSET_ROOT}/audio/sfx/sword-swing.wav`,
    enemyHit: `${ASSET_ROOT}/audio/sfx/enemy-hit.wav`,
    stomp: `${ASSET_ROOT}/audio/sfx/stomp.wav`,
    playerHurt: `${ASSET_ROOT}/audio/sfx/player-hurt.wav`,
    lifeLost: `${ASSET_ROOT}/audio/sfx/life-lost.wav`,
    respawn: `${ASSET_ROOT}/audio/sfx/respawn.wav`,
    coin: `${ASSET_ROOT}/audio/sfx/coin.wav`,
    enemyDefeat: `${ASSET_ROOT}/audio/sfx/enemy-defeat.wav`,
    levelComplete: `${ASSET_ROOT}/audio/sfx/level-complete.wav`,
    routeFailed: `${ASSET_ROOT}/audio/sfx/route-failed.wav`,
  },
  home: {
    background: `${HOME_ROOT}/optimized/bg-title-castle-night.webp`,
    titleScroll: `${HOME_ROOT}/optimized/title-scroll-shadow-runner.webp`,
    optionsScroll: `${HOME_ROOT}/optimized/options-scroll-panel.webp`,
    optionsMenuButton: `${HOME_ROOT}/optimized/options-menu-row-button.webp`,
    blankMenuScroll: `${HOME_ROOT}/optimized/blank-menu-scroll.webp`,
    blankMenuButton: `${HOME_ROOT}/optimized/blank-menu-button.webp`,
    campaignMap: `${HOME_ROOT}/optimized/campaign-map.webp`,
    levelDetailPanel: `${HOME_ROOT}/optimized/level-detail-panel.webp`,
    levelThumbnailFrame: `${HOME_ROOT}/optimized/level-thumbnail-frame.webp`,
    levelThumbnailSquareFrame: `${HOME_ROOT}/optimized/level-thumbnail-square-frame.webp`,
    levelMapScrollPanel: `${HOME_ROOT}/optimized/level-map-scroll-panel.webp`,
    bottomMenuScroll: `${HOME_ROOT}/optimized/bottom-menu-scroll.webp`,
    missionScrollStand: `${HOME_ROOT}/optimized/mission-scroll-stand.webp`,
    starSheet: `${HOME_ROOT}/optimized/star-twinkle-sheet.webp`,
    torchStrip: `${HOME_ROOT}/sliced/torch-flame-8f-192.png`,
    bannerStand: `${HOME_ROOT}/optimized/banner-stand.webp`,
    bannerHanging: `${HOME_ROOT}/sliced/banner-hanging.png`,
    bannerPennant: `${HOME_ROOT}/optimized/banner-pennant.webp`,
  },
  hero: {
    menuIdleCapeStrip: `${ASSET_ROOT}/sprites/strips/shadow-runner-menu-idle-cape-8f-128.png`,
    runStrip: `${ASSET_ROOT}/sprites/strips/shadow-runner-run-6f-128.png`,
    jumpAirStrip: `${ASSET_ROOT}/sprites/strips/shadow-runner-jump-air-6f-128.png`,
    swordAttackStrip: `${ASSET_ROOT}/sprites/strips/shadow-runner-sword-attack-5f-128.png`,
  },
  enemies: {
    clockworkSentryStrip: `${ASSET_ROOT}/sprites/strips/clockwork-sentry-v2-6f-128.png`,
    barrelRollerStrip: `${ASSET_ROOT}/sprites/strips/barrel-roller-v1-5f-128.png`,
    scrollThiefStrip: `${ASSET_ROOT}/sprites/strips/scroll-thief-v1-5f-128.png`,
    towerArcherStrip: `${ASSET_ROOT}/sprites/strips/tower-archer-v1-5f-128.png`,
    candleJesterStrip: `${ASSET_ROOT}/sprites/strips/candle-jester-v1-5f-128.png`,
  },
  gameplay: {
    hudPlaque: `${GAMEPLAY_ROOT}/optimized/hud-status-bar.webp`,
    healthBarFrame: `${GAMEPLAY_ROOT}/optimized/health-bar-frame-clean.webp`,
    healthFill: `${GAMEPLAY_ROOT}/optimized/health-fill.webp`,
    heartFull: `${GAMEPLAY_ROOT}/optimized/heart-full.webp`,
    heartEmpty: `${GAMEPLAY_ROOT}/optimized/heart-empty.webp`,
    coinIcon: `${GAMEPLAY_ROOT}/optimized/coin-icon-clean.webp`,
    levelCompleteBanner: `${GAMEPLAY_ROOT}/optimized/level-complete-banner.webp`,
    touchControlButton: `${GAMEPLAY_ROOT}/optimized/touch-control-button.webp`,
    dpadControlButton: `${GAMEPLAY_ROOT}/optimized/dpad-control-button.webp`,
    swordControlButton: `${GAMEPLAY_ROOT}/optimized/sword-control-button.webp`,
    jumpControlButton: `${GAMEPLAY_ROOT}/optimized/jump-control-button.webp`,
    hitSpark: `${GAMEPLAY_ROOT}/sliced/hit-spark.png`,
    coinSparkleStrip: `${GAMEPLAY_ROOT}/sliced/coin-sparkle-strip.png`,
  },
  level: {
    terrainAtlas: `${LEVEL_ROOT}/terrain/stone-ruins-terrain-v1.png`,
    tiltBridge256: `${LEVEL_ROOT}/terrain/tilt-bridge-v1-256x80.png`,
    coinStrip48: `${LEVEL_ROOT}/collectibles/gold-coin-8f-48.png`,
    spikeRow64: `${LEVEL_ROOT}/hazards/floor-spikes-64x28.png`,
    eastGate96: `${LEVEL_ROOT}/props/east-gate-96x180.png`,
    landingDustStrip: `${LEVEL_ROOT}/vfx/landing-dust-6f-64.png`,
    swordSlashStrip: `${LEVEL_ROOT}/vfx/sword-slash-6f-96.png`,
  },
  levels: {
    eastGateRunThumbnail160: `${LEVEL_ROOT}/level-1/ui/east-gate-run-thumbnail-160x90.webp`,
    eastGateRunThumbnail320: `${LEVEL_ROOT}/level-1/ui/east-gate-run-thumbnail-320x180.webp`,
    lanternMarketThumbnail160: `${LEVEL_ROOT}/level-2/ui/lantern-market-roofs-thumbnail-160x90.webp`,
    lanternMarketThumbnail320: `${LEVEL_ROOT}/level-2/ui/lantern-market-roofs-thumbnail-320x180.webp`,
    lanternMarketBackground: `${LEVEL_ROOT}/level-2/background/lantern-market-roofs-background.webp`,
    ivyViaductBackground: `${LEVEL_ROOT}/level-3/background/ivy-viaduct-background.webp`,
    ivyViaductTerrainHazards: `${LEVEL_ROOT}/level-3/terrain/ivy-viaduct-terrain-hazards-v1-transparent.png`,
    ivyViaductThumbnail160: `${LEVEL_ROOT}/level-3/ui/ivy-viaduct-thumbnail-160x90.webp`,
    ivyViaductThumbnail320: `${LEVEL_ROOT}/level-3/ui/ivy-viaduct-thumbnail-320x180.webp`,
    bellTowerThumbnail160: `${LEVEL_ROOT}/level-4/ui/bell-tower-archives-thumbnail-160x90.webp`,
    bellTowerThumbnail320: `${LEVEL_ROOT}/level-4/ui/bell-tower-archives-thumbnail-320x180.webp`,
    bellTowerBackground: `${LEVEL_ROOT}/level-4/background/bell-tower-archives-background.webp`,
    bellTowerPropsHazards: `${LEVEL_ROOT}/level-4/props/bell-tower-archives-props-hazards-v1-transparent.png`,
    moonheartCrestStrip: `${LEVEL_ROOT}/level-4/collectibles/moonheart-crest-4f-64.png`,
    boostAuraStrip: `${LEVEL_ROOT}/level-4/vfx/boost-aura-4f-128.png`,
    candleFairThumbnail160: `${LEVEL_ROOT}/level-5/ui/candle-fair-ruins-thumbnail-160x90.webp`,
    candleFairThumbnail320: `${LEVEL_ROOT}/level-5/ui/candle-fair-ruins-thumbnail-320x180.webp`,
    candleFairBackground: `${LEVEL_ROOT}/level-5/background/candle-fair-ruins-background.webp`,
    candleFairPropsHazards: `${LEVEL_ROOT}/level-5/props/candle-fair-props-hazards-v1-transparent.png`,
    candleFairTerrainReadable: `${LEVEL_ROOT}/level-5/terrain/candle-fair-terrain-v2-transparent.png`,
    eastGateRunLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-1-east-gate-run-location-button.webp`,
    lanternMarketLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-2-lantern-market-roofs-location-button.webp`,
    ivyViaductLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-3-ivy-viaduct-location-button.webp`,
    bellTowerLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-4-bell-tower-archives-location-button.webp`,
    candleFairLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-5-candle-fair-ruins-location-button.webp`,
    clockmakerYardLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-6-clockmaker-yard-location-button.webp`,
    moonlitCausewayLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-7-moonlit-causeway-location-button.webp`,
    courierCatacombsLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-8-courier-catacombs-location-button.webp`,
    captainGateLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-9-captain-gate-location-button.webp`,
    dawnRelaySpireLocationButton: `${HOME_ROOT}/optimized/map-location-buttons/level-10-dawn-relay-spire-location-button.webp`,
  },
} as const
